/**
 * Every user-facing string of МебелИС, centralized in Macedonian (Cyrillic).
 * Code identifiers, the database schema and comments stay in English.
 */

export const t = {
  appName: "МебелИС",
  companyName: "Мебел ДОО — Битола",
  appTagline:
    "Интегриран информациски систем за управување со производствен процес",

  nav: {
    dashboard: "Контролна табла",
    customers: "Клиенти",
    products: "Производи",
    warehouse: "Магацин",
    orders: "Нарачки",
    production: "Производство",
    quality: "Квалитет",
    reports: "Извештаи",
  },

  common: {
    loading: "Се вчитува…",
    error: "Настана грешка. Обидете се повторно.",
    retry: "Обиди се повторно",
    empty: "Нема податоци за прикажување.",
    save: "Зачувај",
    cancel: "Откажи",
    add: "Додади",
    edit: "Измени",
    delete: "Избриши",
    confirmDelete: "Дали сте сигурни дека сакате да го избришете записот?",
    search: "Пребарај…",
    actions: "Акции",
    close: "Затвори",
    denars: "ден.",
    pieces: "пар.",
    date: "Датум",
    status: "Статус",
    quantity: "Количина",
    total: "Вкупно",
    required: "Задолжително поле",
    yes: "Да",
    no: "Не",
    all: "Сите",
  },

  status: {
    NEW: "Нова",
    IN_PRODUCTION: "Во производство",
    QC: "Контрола на квалитет",
    READY: "Во магацин",
    DELIVERED: "Испорачана",
  } as Record<string, string>,

  poStatus: {
    OPEN: "Отворен",
    WAITING_QC: "Чека контрола",
    COMPLETED: "Завршен",
  } as Record<string, string>,

  dashboard: {
    title: "Контролна табла",
    subtitle: "Преглед на работењето на претпријатието во реално време",
    activeOrders: "Активни нарачки",
    inProduction: "Во производство",
    lowStock: "Материјали со ниска залиха",
    deliveredThisMonth: "Испорачани овој месец",
    defectRate: "Стапка на неисправни",
    finishedGoods: "Готови производи на залиха",
    ordersByStatus: "Нарачки по статус",
    monthlyOrders: "Нарачки по месец",
    recentOrders: "Последни нарачки",
    lowStockTitle: "Критични залихи",
    lowStockOk: "Сите материјали се над минималното ниво.",
    material: "Материјал",
    available: "Расположливо",
    minimum: "Минимум",
  },

  customers: {
    title: "Клиенти",
    subtitle: "Евиденција на клиентите на претпријатието",
    name: "Назив",
    contact: "Контакт лице",
    phone: "Телефон",
    email: "Е-пошта",
    city: "Град",
    ordersCount: "Нарачки",
    addTitle: "Нов клиент",
    editTitle: "Измени клиент",
    deleteBlocked: "Клиентот не може да се избрише бидејќи има нарачки.",
  },

  products: {
    title: "Производи",
    subtitle: "Каталог на производи и потребни материјали (норматив)",
    code: "Шифра",
    name: "Назив",
    category: "Категорија",
    price: "Продажна цена",
    stock: "Залиха",
    bom: "Норматив на материјали",
    bomShort: "Материјали",
    bomPerUnit: "Потребни материјали за 1 единица производ",
    materialCost: "Трошок за материјали",
    addTitle: "Нов производ",
    editTitle: "Измени производ",
    addMaterial: "Додади материјал",
    noBom: "Нема дефинирани материјали за овој производ.",
    deleteBlocked: "Производот не може да се избрише бидејќи има нарачки.",
    categories: ["Маси", "Столици", "Плакари", "Кревети", "Полици"],
  },

  warehouse: {
    title: "Магацин",
    subtitle: "Состојба на залихи на материјали и готови производи",
    materials: "Материјали (суровини)",
    products: "Готови производи",
    material: "Материјал",
    unit: "Единица мерка",
    unitPrice: "Единечна цена",
    stock: "Залиха",
    minStock: "Мин. залиха",
    stockValue: "Вредност на залиха",
    lowStockBadge: "Ниска залиха",
    restock: "Набавка",
    restockTitle: "Набавка на материјал",
    restockQty: "Количина за набавка",
    addTitle: "Нов материјал",
    editTitle: "Измени материјал",
    movements: "Последни движења на залихата",
    movementDate: "Датум",
    movementItem: "Ставка",
    movementChange: "Промена",
    movementReason: "Основ",
    reasons: {
      seed: "Почетна состојба",
      purchase: "Набавка",
      production_use: "Потрошено во производство",
      production_in: "Произведено",
      delivery: "Испорака",
      adjustment: "Корекција",
    } as Record<string, string>,
  },

  orders: {
    title: "Нарачки",
    subtitle: "Евиденција и следење на нарачките од клиентите",
    number: "Нарачка",
    customer: "Клиент",
    product: "Производ",
    addTitle: "Нова нарачка",
    created: "Креирана",
    materialCheck: "Проверка на материјали",
    materialOk: "Има доволно материјали за производство.",
    materialMissing: "Недостигаат материјали:",
    startProduction: "Започни производство",
    deliver: "Испорачај",
    deliverBlocked: (available: number) =>
      `Недоволна залиха на готови производи (расположливо: ${available}).`,
    startBlocked: "Производството не може да започне — недостигаат материјали. Извршете набавка во Магацин.",
    valueTotal: "Вредност",
  },

  production: {
    title: "Производство",
    subtitle: "Производствени налози и нивниот статус",
    poNumber: "Налог",
    order: "Нарачка",
    product: "Производ",
    started: "Започнат",
    completed: "Завршен",
    finish: "Заврши производство",
    finishHint: "Со завршувањето, налогот преминува во контрола на квалитет.",
    empty: "Нема производствени налози.",
    materialsUsed: "Потрошени материјали",
  },

  quality: {
    title: "Контрола на квалитет",
    subtitle: "Проверка на произведените единици пред влез во магацин",
    pending: "Налози што чекаат контрола",
    history: "Извршени контроли",
    produced: "Произведени",
    good: "Исправни",
    defect: "Неисправни",
    note: "Забелешка",
    submit: "Потврди контрола",
    invalidSplit: "Исправни + неисправни мора да е еднакво на произведената количина.",
    noPending: "Нема налози што чекаат контрола на квалитет.",
    defectPercent: "% неисправни",
  },

  reports: {
    title: "Извештаи",
    subtitle: "Аналитички преглед на работењето",
    monthlyProduction: "Произведени единици по месец",
    monthlyRevenue: "Вредност на испорачани нарачки по месец",
    defectByProduct: "Стапка на неисправни по производ",
    topProducts: "Најнарачувани производи",
    topCustomers: "Клиенти по број на нарачки",
    stockValueTitle: "Вредност на залихи",
    materialsValue: "Материјали",
    productsValue: "Готови производи",
    unitsProduced: "произведени единици",
    unitsGood: "исправни",
    unitsDefect: "неисправни",
  },

  footer: {
    note: "Дипломски труд · Прототип на информациски систем за производствено претпријатие",
  },
} as const;

export type Strings = typeof t;
